// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/chongyanovo/go-zzz/core"
	"github.com/chongyanovo/go-zzz/core/bootstrap"
	"github.com/chongyanovo/go-zzz/core/logger"
)

// Injectors from wire.go:

func InitApp() (core.Application, error) {
	viper := bootstrap.NewViper()
	config := bootstrap.NewConfig(viper)
	db := bootstrap.NewMysql(config)
	cmdable := bootstrap.NewRedis(config)
	zapLogger := bootstrap.NewZap(config)
	loggerLogger := logger.NewZapLogger(zapLogger)
	engine := bootstrap.NewServer(config)
	application := core.NewApplication(config, viper, db, cmdable, loggerLogger, engine)
	return application, nil
}
